SELF_DIR         := $(dir $(lastword $(MAKEFILE_LIST)))
EXTENSION        = crankshaft
PACKAGE          = crankshaft
EXTVERSION       = $(shell grep default_version $(SELF_DIR)/src/pg/$(EXTENSION).control | sed -e "s/default_version[[:space:]]*=[[:space:]]*'\([^']*\)'/\1/")
RELEASE_VERSION ?= $(EXTVERSION)
SED              = sed
