# Install the package (needs root privileges)
install:
	pip install ./crankshaft --upgrade

# Test from source code
test:
	(cd crankshaft && nosetests test/)

# Test currently installed package
testinstalled:
	nosetests crankshaft/test/
